apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mini-modern-cluster
  region: us-east-1
  version: "1.32"

iam:
  serviceRoleARN: arn:aws:iam::934010667284:role/EKSControlPlaneRole-311147.80561755016944

nodeGroups:
  - name: ng-group
    instanceType: t2.micro
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    iam:
      instanceRoleARN: arn:aws:iam::934010667284:role/EKSNodeInstanceRole-311147.80561755016944
      instanceProfileARN: arn:aws:iam::934010667284:instance-profile/EKSNodeInstanceProfile-311147.80561755016944

