
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
        - name: auth-service
          # Replace <your-aws-account-id> and <region> accordingly
          image: 934010667284.dkr.ecr.us-east-1a.amazonaws.com/auth-service:latest
          ports:
            - containerPort: 80
          env:
            # Replace the following environment values with your actual DB credentials
            - name: DB_HOST
              value: mini-db.cluster-cmr68ieao9xg.us-east-1.rds.amazonaws.com        # Replace accordingly
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: mini-db                          # Replace accordingly
            - name: DB_USER
              value: Whiz_User_311147.80561755016944                      # Replace accordingly
            - name: DB_PASSWORD
              value: Password0102                      # Replace accordingly
